default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DB_NAME'] || "nuuvem_development" %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  # username: <%= ENV['DB_USER'] || "postgres" %>
  # password: <%= ENV['DB_PASS'] || "postgres" %>
  # host: <%= ENV['DB_HOST'] || "localhost" %>
  # port: <%= ENV['DB_PORT'] || 5432 %>

test:
  <<: *default
  database: nuuvem_test

production:
  <<: *default
